version: '3.8'
services:
  persistence:
    build:
      context: .
      dockerfile: ./persistence/Dockerfile.dev
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/weeky
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - URL=http://persistence:8081
  webapp:
    build:
      context: .
      dockerfile: ./webapp/Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PERSISTENCE_API=http://persistence:8081
      - URL=http://webapp:8080
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=weeky
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432