name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:

  deploy:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push weeky-persistence
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}"
        file: "persistence/Dockerfile"
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/weeky-persistence:latest
    - name: Build and push weeky-webapp
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}"
        file: "webapp/Dockerfile"
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/weeky-webapp:latest
